version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - app
    
   

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mongodb


volumes:
  mongodb_data:
